### ISSUE TITLE
Subscribe-to-cart functionality

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-to-all-the-things#15]
All the infrastructure for this is already in place - the only task left seems to be the processing/saving of subscription schemes defined via **WooCommerce > Settings > Subscriptions**.

**Comment by thenbrent** [comment]
@franticpsyx what's your opinion releasing this as a separate _*Subscribe to Cart*_ plugin instead of  bundling it within _*Subscribe to All the Things*_?

I think having a singular focus for mini-extensions will make it easier for users to understand what they do (and possibly also easier for us to maintain). So we could make _*Subscribe to All the Things*_ purely about offering subscription options for non-subscription products (in which case the plugin name becomes a little bit of a misnomer haha).

But I suspect that perhaps some of the necessary logic for cart subscriptions is bundled in here already so that may provide a strong technical argument for bundling them? (unless we could abstract it into a shared library)

**Comment by louis2b** [comment]
Maybe what is related to the product page and what is related to the cart page should be treated separately. In the current version, the fact that customers can still change subs scheme from the cart page could also distract them from continuing to checkout. 

it could be easier to separate both, with one option to _create subs schemes for non subs products_, on the product page, but once they are in the checkout the scheme cannot be changed so they are not disctracted.
And then another process for _subscribe to cart_ option. where you fill your basket and you make the subscription scheme decision on the cart page.

I see those as 2 different way of selling things, what do you think ?

**Comment by franticpsyx** [comment]
@louis2b For now, it might indeed make sense to add a filter that prevents sub options from showing up in the cart page.

@thenbrent 

>But I suspect that perhaps some of the necessary logic for cart subscriptions is bundled in here already so that may provide a strong technical argument for bundling them? (unless we could abstract it into a shared library)

Exactly. The core "logic" is in SATT, so if we make a separate plugin for this it would need to be a SATT plugin, which is, in turn, a WC Subscriptions plugin.

I think it makes sense to enable that feature here, and basically use SATT as a "playground" for features made possible due to the subs/product decoupling. That will probably help generate more traction for SATT, and get as much feedback as possible about the workflow it is introducing.

In the long run, we could eventually port the core logic into Subscriptions, and see how the individual features can be distributed/enabled.

**Comment by franticpsyx** [comment]
@louis2b - actually, there is a filter already - `wcsatt_show_cart_item_options`

**Comment by thenbrent** [comment]
@franticpsyx sounds good. :+1:
