### ISSUE TITLE
Cart totals are incorrect with more than one item with subscription options

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-to-all-the-things#31]
@thenbrent and @franticpsyx I found another issue. If two items that have subscription options are added to the cart, the sub-total and recurring total are not calculating correctly.

![Cart Sub-Total and Recurring Total Incorrect](https://cldup.com/Bg3SDltUcV.png)

It appears to only calculate the last item in the cart.

**Comment by seb86** [comment]
Let me know if you get the same error.

**Comment by seb86** [comment]
@thenbrent, @franticpsyx If you change the subscription option on the first item, then it shows correctly under Subtotal and Recurring Total but not before. If you leave the options as is and just press "Update Cart" nothing changes.

![Change option on the first item](https://cldup.com/LThRfCkctL.png)

**Comment by thenbrent** [comment]
> If you change the subscription option on the first item, then it shows correctly under Subtotal and Recurring Total

@seb86 in the first screenshot, you have the price on the `2016 Subaru ...` product set to be for `290€ for 1 month`. That means it is only one payment - there is no recurring total. That's why the extra 290€ is not shown on the recurring totals section.

That's also why when you change it to be `250€ / month for 6 months` the recurring total is displayed correctly.

This is correct behaviour.

**Comment by seb86** [comment]
@thenbrent Sorry about that. I clearly overlooked it.

**Comment by thenbrent** [comment]
@seb86 no problem, we see this confusion occasionally and do have an option issue to change the UI to avoid it with v2.1 of Subscriptions: https://github.com/Prospress/woocommerce-subscriptions/issues/613

**Comment by seb86** [comment]
@thenbrent OK. That sounds great.
